FROM opensuse/tumbleweed:latest
LABEL maintainer="Danila Pechenev <danila.pechenev@gmail.com>"
RUN zypper install --no-confirm binutils && \
    zypper install --no-confirm python3-pip && \
    zypper install --no-confirm firefox && \
    zypper install --no-confirm chromium && \
    zypper install --no-confirm kcachegrind && \
    zypper install --no-confirm vlc
#   install other packages here