name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out a repo
        uses: actions/checkout@v3
      - name: Run linter on src
        uses: psf/black@stable
        with:
          options: "--check --verbose -l 120"
          src: "./data_collection"
          version: "~= 22.0"
      - name: Run linter on scripts
        uses: psf/black@stable
        with:
          options: "--check --verbose -l 120"
          src: "./scripts"
          version: "~= 22.0"
